#!/bin/sh
#
# Gradle wrapper script — generated by `gradle wrapper`
# This file is the standard Gradle wrapper launcher for *nix systems.
#
# If this script does not exist yet, run:
#   gradle wrapper --gradle-version 8.4
# in the sonata-android/ directory (requires Gradle installed locally).
#

APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")

# Resolve links
PRG="$0"
while [ -h "$PRG" ]; do
  ls=$(ls -ld "$PRG")
  link=$(expr "$ls" : '.*-> \(.*\)$')
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=$(dirname "$PRG")"/$link"
  fi
done
SAVED="$(pwd)"
cd "$(dirname "$PRG")" >/dev/null
APP_HOME="$(pwd -P)"
cd "$SAVED" >/dev/null

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the OS
case "$(uname)" in
  CYGWIN* | MINGW*)
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")
    ;;
esac

exec "$JAVACMD" "$@" \
  -classpath "$CLASSPATH" \
  org.gradle.wrapper.GradleWrapperMain \
  "$@"
